### ISSUE TITLE
shutter-icon.svg does not show up as intended on github pages deployment

### ISSUE THREAD

**Issue by simon-s-99** [adamkumlin/frontend-image-search#58]
![image](https://github.com/adamkumlin/frontend-image-search/assets/142667693/d142da87-98ad-4402-b037-baa2146ff346)

**Comment by adamkumlin** [comment]
hmm, weird. for me it does show up as intended:

![Screenshot 2024-02-06 222416](https://github.com/adamkumlin/frontend-image-search/assets/71759619/5956484a-46cb-438e-bd4d-2cce6b127ae1)

maybe it's something to do with cookies/site cache?

**Comment by adamkumlin** [comment]
oh never mind i just saw you pushed a new version. my bad

**Comment by simon-s-99** [comment]
Yeah no this was a caching error, reverted change 👍
