### ISSUE TITLE
fix responsive design for footer and pageButtons

### ISSUE THREAD

**Issue by simon-s-99** [adamkumlin/frontend-image-search#59]
![image](https://github.com/adamkumlin/frontend-image-search/assets/142667693/bf22b949-f387-4d3b-b6a4-5d4fa12f1313)

**Comment by adamkumlin** [comment]
it seems to be the responsive mode that's playing tricks on us again:

https://github.com/adamkumlin/frontend-image-search/assets/71759619/fa036fba-1e4c-43e8-870d-3d33e1fd048e

**Comment by simon-s-99** [comment]
i tested this on my mobile phone, the footer text is fine since my resolution is big enough but the numbered buttons were broken

great idea to remove them though 👍
